import Head from "next/head";
import Prismic from "@prismicio/client";
import Image from "next/image";
import Link from "next/link";

export const apiEndpoint = "https://nextblogjs.cdn.prismic.io/api/v2";
const Client = () => Prismic.client(apiEndpoint);

export async function getStaticProps() {
  const { results } = await Client().query("");

  return {
    props: {
      results,
    },
  };
}

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Prismic Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        {results.map((item, index) => (
          <div key={index}>
            <Link passHref href={`/posts/${item.id}`}>
              <div style={{ padding: "50px", border: "black solid thin" }}>
                <h1>{item.data.title[0].text}</h1>
                <Image
                  alt="stock photo"
                  src={item.data.image.url}
                  height={200}
                  width={300}
                />
              </div>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
}
